# Generated by Django 3.1.4 on 2020-12-31 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0002_quiz_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='Branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ME', 'ME')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='Sem',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], max_length=20, null=True),
        ),
    ]
