# Generated by Django 3.1.4 on 2021-01-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0004_auto_20201231_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time',
            field=models.IntegerField(default=5, help_text='Enter total Time in Minutes ! '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='Branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ME', 'ME'), ('ECE', 'ECE'), ('EX', 'EX'), ('CE', 'CE')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='Sem',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='total_marks',
            field=models.IntegerField(help_text='Enter total Marks Note:Each Question is of 1 Marks ! '),
        ),
    ]
