# Generated by Django 3.1.4 on 2020-12-29 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('Year', models.IntegerField()),
                ('Branch', models.CharField(max_length=20)),
                ('RollNo', models.CharField(max_length=20, unique=True)),
                ('signup_confirmation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('Branch', models.CharField(max_length=20)),
                ('UID', models.CharField(max_length=20, unique=True)),
                ('signup_confirmation', models.BooleanField(default=False)),
            ],
        ),
    ]
