# Generated by Django 3.1.4 on 2020-12-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_auto_20201229_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='UID',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
