# Generated by Django 3.1.4 on 2020-12-31 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_auto_20201229_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Year',
            field=models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Branch',
            field=models.CharField(blank=True, choices=[('CSE', 'CSE'), ('ME', 'ME')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Year',
            field=models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Branch',
            field=models.CharField(blank=True, choices=[('CSE', 'CSE'), ('ME', 'ME')], max_length=20, null=True),
        ),
    ]
