# Generated by Django 3.1.4 on 2020-12-31 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_auto_20201231_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Sem',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Sem',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], max_length=20, null=True),
        ),
    ]
